// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ScuolaDbContext))]
    partial class ScuolaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Aula", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AulaId"));

                    b.Property<int>("Capienza")
                        .HasColumnType("int");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AulaId");

                    b.ToTable("Aule");
                });

            modelBuilder.Entity("Models.Classe", b =>
                {
                    b.Property<int>("ClasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClasseId"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<string>("Sezione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClasseId");

                    b.ToTable("Classi");
                });

            modelBuilder.Entity("Models.Corso", b =>
                {
                    b.Property<int>("CorsoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorsoId"));

                    b.Property<int>("Crediti")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCorso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CorsoId");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("Models.Docente", b =>
                {
                    b.Property<int>("DocenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocenteId"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocenteId");

                    b.ToTable("Docenti");
                });

            modelBuilder.Entity("Models.Iscrizione", b =>
                {
                    b.Property<int>("IscrizioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IscrizioneId"));

                    b.Property<string>("AnnoAccademico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.HasKey("IscrizioneId");

                    b.HasIndex("CorsoId");

                    b.HasIndex("StudenteId", "CorsoId", "AnnoAccademico")
                        .IsUnique();

                    b.ToTable("Iscrizioni");
                });

            modelBuilder.Entity("Models.Lezione", b =>
                {
                    b.Property<int>("LezioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LezioneId"));

                    b.Property<string>("Argomento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inizio")
                        .HasColumnType("datetime2");

                    b.HasKey("LezioneId");

                    b.HasIndex("AulaId");

                    b.HasIndex("CorsoId");

                    b.HasIndex("DocenteId");

                    b.ToTable("Lezioni");
                });

            modelBuilder.Entity("Models.Presenza", b =>
                {
                    b.Property<int>("PresenzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresenzaId"));

                    b.Property<int>("LezioneId")
                        .HasColumnType("int");

                    b.Property<bool>("Stato")
                        .HasColumnType("bit");

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.HasKey("PresenzaId");

                    b.HasIndex("LezioneId");

                    b.HasIndex("StudenteId");

                    b.ToTable("Presenze");
                });

            modelBuilder.Entity("Models.Studente", b =>
                {
                    b.Property<int>("StudenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudenteId"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudenteId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Models.Valutazione", b =>
                {
                    b.Property<int>("ValutazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValutazioneId"));

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("PunteggioMassimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValutazioneId");

                    b.HasIndex("CorsoId");

                    b.HasIndex("DocenteId");

                    b.ToTable("Valutazioni");
                });

            modelBuilder.Entity("Models.Voto", b =>
                {
                    b.Property<int>("VotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VotoId"));

                    b.Property<string>("Commento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Punteggio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.Property<int>("ValutazioneId")
                        .HasColumnType("int");

                    b.HasKey("VotoId");

                    b.HasIndex("StudenteId");

                    b.HasIndex("ValutazioneId");

                    b.ToTable("Voti");
                });

            modelBuilder.Entity("Models.Iscrizione", b =>
                {
                    b.HasOne("Models.Classe", "Classe")
                        .WithMany("Iscrizioni")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Corso", "Corso")
                        .WithMany("Iscrizioni")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Studente", "Studente")
                        .WithMany("Iscrizione")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Corso");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("Models.Lezione", b =>
                {
                    b.HasOne("Models.Aula", "Aula")
                        .WithMany("Lezioni")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Corso", "Corso")
                        .WithMany("Lezioni")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Docente", "Docente")
                        .WithMany("Lezioni")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Corso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Models.Presenza", b =>
                {
                    b.HasOne("Models.Lezione", "Lezione")
                        .WithMany("Presenze")
                        .HasForeignKey("LezioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Studente", "Studente")
                        .WithMany("Presenze")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lezione");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("Models.Valutazione", b =>
                {
                    b.HasOne("Models.Corso", "Corso")
                        .WithMany("Valutazioni")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Docente", "Docente")
                        .WithMany("Valutazioni")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Models.Voto", b =>
                {
                    b.HasOne("Models.Studente", "Studente")
                        .WithMany("Voti")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Valutazione", "Valutazione")
                        .WithMany("Voti")
                        .HasForeignKey("ValutazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studente");

                    b.Navigation("Valutazione");
                });

            modelBuilder.Entity("Models.Aula", b =>
                {
                    b.Navigation("Lezioni");
                });

            modelBuilder.Entity("Models.Classe", b =>
                {
                    b.Navigation("Iscrizioni");
                });

            modelBuilder.Entity("Models.Corso", b =>
                {
                    b.Navigation("Iscrizioni");

                    b.Navigation("Lezioni");

                    b.Navigation("Valutazioni");
                });

            modelBuilder.Entity("Models.Docente", b =>
                {
                    b.Navigation("Lezioni");

                    b.Navigation("Valutazioni");
                });

            modelBuilder.Entity("Models.Lezione", b =>
                {
                    b.Navigation("Presenze");
                });

            modelBuilder.Entity("Models.Studente", b =>
                {
                    b.Navigation("Iscrizione");

                    b.Navigation("Presenze");

                    b.Navigation("Voti");
                });

            modelBuilder.Entity("Models.Valutazione", b =>
                {
                    b.Navigation("Voti");
                });
#pragma warning restore 612, 618
        }
    }
}
